### ISSUE TITLE
Regarding data extraction

### ISSUE THREAD

**Issue by Ummiruhina** [sgoutam/Reversible-Data-Hiding#1]
Here i have added text data in image embedding part is completed,but extraction time text is not recovered please help m what modifications is needed

**Comment by Ummiruhina** [comment]
Hello sir

**Comment by sgoutam** [comment]
Hi.
During extraction the text recovered from the image is stored in the array arr[].
```
%Retreive the message from the Reveived Image and obtain the original image
for i=1:row
    for j=1:col
         if img2(i,j)==a
             arr(ptr1)=0;
             ptr1=ptr1+1;
         elseif img2(i,j)== a+1
              img2(i,j)=a;
             arr(ptr1)=1;
             ptr1=ptr1+1;
          end;
    end;
end;
```

In this code snippet, we're basically doing the reverse of the embedding mechanism to find the pixels that have been altered and subsequently modifying their respective value (toggling 0/1) in the array arr[].

**Comment by Ummiruhina** [comment]
Yes i.e getting for randomly generated data.i m embedding some text messgae for eg "shaikh u" this data i want to add in image and recover from that image.after extraction my original data i want..i.e not coming Viva this code.. Please reply m what modifications needed for that type of requirement

**Comment by Ummiruhina** [comment]
Please reply as soon as possible

**Comment by sgoutam** [comment]
Sorry for the late reply.
This can be achieved by converting the text input into a string of 0/1s and then using this binary array as input in the embedding code.
This particular code was developed as an academic project to validate the metrics for certain RDH algorithms, therefore a module such as you seek has not been developed. But out of the top of my head, I'd say that with some modifications like converting ASCII string to Binary array might work.
But you also need to make sure that while decoding the same binary array, you must use the specific set of process meant for the algorithm used to encode.

**Comment by Ummiruhina** [comment]
Yes i did embedding part using conversion but at receiver side extraction is not coming proper output.. can u give m code for text embedding and text extraction this is my me  project

**Comment by Ummiruhina** [comment]
Please give m updated code, actually its urgent i have to give comparative result in different data hiding techniques ,bcz of this my ME  project is pending

**Comment by sgoutam** [comment]
I apologize as currently I do not have enough bandwidth to work on the modifications that you have requested. I will try to make enhancements to the code, but currently I am unable to work on this.
As I had mentioned, this was one of my undergrad projects, so this is a quite naive implementation of RDH techniques. I would suggest you to try finding more advanced RDH implementations.
Thank you.
